# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
 
# To get started:
 
# 1. Add your Datadog API (DD_API_KEY) and Application Key (DD_APP_KEY) as secrets to your GitHub repository. For more information, see: https://docs.datadoghq.com/account_management/api-app-keys/.
# 2. Start using the action within your workflow
 
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
 
        
name: Run Synthetic tests using the test public IDs
jobs:
  e2e_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # datadog_site: app.datadoghq.com
      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v0.3.0
        with:
          api_key: ${{secrets.DD_API_KEY}}
          app_key: ${{secrets.DD_APP_KEY}}
          public_ids: 'hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb, hmj-6qp-ydb'
